// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn8mop8c7zsS0RGpp1TvtzKEztmYsN3RE',
    appId: '1:213008457005:web:bec626d52f9a07bec3c7a4',
    messagingSenderId: '213008457005',
    projectId: 'recipe-app-8cb60',
    authDomain: 'recipe-app-8cb60.firebaseapp.com',
    storageBucket: 'recipe-app-8cb60.firebasestorage.app',
    measurementId: 'G-9XSZ3FQ6GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZuKdsnGWYutTVtVKJ6G4aJRdqAoaGjSU',
    appId: '1:213008457005:android:285c3a0a954a092fc3c7a4',
    messagingSenderId: '213008457005',
    projectId: 'recipe-app-8cb60',
    storageBucket: 'recipe-app-8cb60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFa8QRmezFzwE6roOnfZjoUtpwkKYwsc',
    appId: '1:213008457005:ios:a98f437a419fc0cbc3c7a4',
    messagingSenderId: '213008457005',
    projectId: 'recipe-app-8cb60',
    storageBucket: 'recipe-app-8cb60.firebasestorage.app',
    iosClientId: '213008457005-454tq89rtgl0j4rs0ipti75jdvj2nm9g.apps.googleusercontent.com',
    iosBundleId: 'com.myrecipe.com.myrecipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFa8QRmezFzwE6roOnfZjoUtpwkKYwsc',
    appId: '1:213008457005:ios:a98f437a419fc0cbc3c7a4',
    messagingSenderId: '213008457005',
    projectId: 'recipe-app-8cb60',
    storageBucket: 'recipe-app-8cb60.firebasestorage.app',
    iosBundleId: 'com.myrecipe.com.myrecipeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn8mop8c7zsS0RGpp1TvtzKEztmYsN3RE',
    appId: '1:213008457005:web:2efbc64236383fa1c3c7a4',
    messagingSenderId: '213008457005',
    projectId: 'recipe-app-8cb60',
    authDomain: 'recipe-app-8cb60.firebaseapp.com',
    storageBucket: 'recipe-app-8cb60.firebasestorage.app',
    measurementId: 'G-0RS842D7YV',
  );
}